services:
  postgres:
    image: postgis/postgis:15-3.4
    container_name: postgres-pathao-new
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pathao
    ports:
      - "5433:5432"
    volumes:
      - pathao_postgres_new:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pathao_postgres_new:
