services:
  postgres:
    image: postgis/postgis:15-3.4
    container_name: postgres-pathao
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pathao
    ports:
      - "5432:5432"
    volumes:
      - pathao_postgres:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis-pathao
    ports:
      - "6379:6379"
    volumes:
      - pathao_redis:/data
    restart: unless-stopped

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander-pathao
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  pathao_postgres:
  pathao_redis:
